/* puchi_unredirect.h - included by puchi_impl.c right after the last upstream
 * .c file.  Removes every redirect and restores whatever the host's headers
 * had defined under those names (e.g. MSVC's stderr macro). */
#undef getc
#pragma pop_macro("getc")
#undef ungetc
#pragma pop_macro("ungetc")
#undef putc
#pragma pop_macro("putc")
#undef fputc
#pragma pop_macro("fputc")
#undef fputs
#pragma pop_macro("fputs")
#undef fflush
#pragma pop_macro("fflush")
#undef fclose
#pragma pop_macro("fclose")
#undef clearerr
#pragma pop_macro("clearerr")
#undef ferror
#pragma pop_macro("ferror")
#undef fgets
#pragma pop_macro("fgets")
#undef fileno
#pragma pop_macro("fileno")
#undef fseek
#pragma pop_macro("fseek")
#undef ftell
#pragma pop_macro("ftell")
#undef fread
#pragma pop_macro("fread")
#undef fwrite
#pragma pop_macro("fwrite")
#undef fopen
#pragma pop_macro("fopen")
#undef select
#pragma pop_macro("select")
#undef usleep
#pragma pop_macro("usleep")
#undef poll
#pragma pop_macro("poll")
#undef fcntl
#pragma pop_macro("fcntl")
#undef shutdown
#pragma pop_macro("shutdown")
#undef stderr
#pragma pop_macro("stderr")
#undef FD_ZERO
#pragma pop_macro("FD_ZERO")
#undef FD_SET
#pragma pop_macro("FD_SET")
#undef FD_ISSET
#pragma pop_macro("FD_ISSET")
#undef getenv
#pragma pop_macro("getenv")
#undef setenv
#pragma pop_macro("setenv")
#undef unsetenv
#pragma pop_macro("unsetenv")
#undef strerror
#pragma pop_macro("strerror")
#undef read
#pragma pop_macro("read")
#undef write
#pragma pop_macro("write")
#undef close
#pragma pop_macro("close")
#undef lseek
#pragma pop_macro("lseek")
#undef fstat
#pragma pop_macro("fstat")
#undef stat
#pragma pop_macro("stat")
#undef snprintf
#pragma pop_macro("snprintf")
#undef sscanf
#pragma pop_macro("sscanf")
#undef exit
#pragma pop_macro("exit")
#undef malloc
#pragma pop_macro("malloc")
#undef calloc
#pragma pop_macro("calloc")
#undef free
#pragma pop_macro("free")
#undef isalpha
#pragma pop_macro("isalpha")
#undef isdigit
#pragma pop_macro("isdigit")
#undef isxdigit
#pragma pop_macro("isxdigit")
#undef isspace
#pragma pop_macro("isspace")
#undef tolower
#pragma pop_macro("tolower")
#undef toupper
#pragma pop_macro("toupper")
#undef strcasecmp
#pragma pop_macro("strcasecmp")
#undef strncasecmp
#pragma pop_macro("strncasecmp")
#undef getenv_s
#pragma pop_macro("getenv_s")
#undef _putenv_s
#pragma pop_macro("_putenv_s")
#ifdef _WIN32
#undef F_GETFL
#pragma pop_macro("F_GETFL")
#undef F_SETFL
#pragma pop_macro("F_SETFL")
#undef O_NONBLOCK
#pragma pop_macro("O_NONBLOCK")
#endif
