;; Embeddable subset of tests/lib-tests.scm for the puchi harness.
;; Each import below was gated alone under the tower harness (exit 0).
;;
;; Omitted classes:
;;   - OS-bound: process / system / tar / filesystem / io-test (/etc/passwd)
;;   - Missing harness static FFI: srfi 18/27/95/144/160, chibi json/sha2/time
;;   - Transitive pull of those: srfi 14/35/101/116/128/132/113/125/146/166,
;;     doc-test, log-test, show c-test, prime, rsa, …

(import (scheme base)
        (chibi test)
        (rename (srfi 1 test) (run-tests run-srfi-1-tests))
        (rename (srfi 2 test) (run-tests run-srfi-2-tests))
        (rename (srfi 16 test) (run-tests run-srfi-16-tests))
        (rename (srfi 26 test) (run-tests run-srfi-26-tests))
        (rename (srfi 38 test) (run-tests run-srfi-38-tests))
        (rename (srfi 41 test) (run-tests run-srfi-41-tests))
        (rename (srfi 69 test) (run-tests run-srfi-69-tests))
        (rename (srfi 99 test) (run-tests run-srfi-99-tests))
        (rename (srfi 117 test) (run-tests run-srfi-117-tests))
        (rename (srfi 121 test) (run-tests run-srfi-121-tests))
        (rename (srfi 127 test) (run-tests run-srfi-127-tests))
        (rename (srfi 129 test) (run-tests run-srfi-129-tests))
        (rename (srfi 130 test) (run-tests run-srfi-130-tests))
        (rename (srfi 133 test) (run-tests run-srfi-133-tests))
        (rename (srfi 134 test) (run-tests run-srfi-134-tests))
        (rename (srfi 139 test) (run-tests run-srfi-139-tests))
        (rename (srfi 151 test) (run-tests run-srfi-151-tests))
        (rename (srfi 158 test) (run-tests run-srfi-158-tests))
        (rename (srfi 211 test) (run-tests run-srfi-211-tests))
        (rename (srfi 219 test) (run-tests run-srfi-219-tests))
        (rename (srfi 229 test) (run-tests run-srfi-229-tests))
        (rename (srfi 253 test) (run-tests run-srfi-253-tests))
        (rename (srfi 273 test) (run-tests run-srfi-273-tests))
        (rename (scheme bytevector-test) (run-tests run-scheme-bytevector-tests))
        (rename (chibi assert-test) (run-tests run-assert-tests))
        (rename (chibi base64-test) (run-tests run-base64-tests))
        (rename (chibi bytevector-test) (run-tests run-bytevector-tests))
        (rename (chibi crypto md5-test) (run-tests run-md5-tests))
        (rename (chibi generic-test) (run-tests run-generic-tests))
        (rename (chibi iset-test) (run-tests run-iset-tests))
        (rename (chibi loop-test) (run-tests run-loop-tests))
        (rename (chibi match-test) (run-tests run-match-tests))
        (rename (chibi mime-test) (run-tests run-mime-tests))
        (rename (chibi numeric-test) (run-tests run-numeric-tests))
        (rename (chibi parse-test) (run-tests run-parse-tests))
        (rename (chibi pathname-test) (run-tests run-pathname-tests))
        (rename (chibi regexp-test) (run-tests run-regexp-tests))
        (rename (chibi scribble-test) (run-tests run-scribble-tests))
        (rename (chibi string-test) (run-tests run-string-tests))
        (rename (chibi sxml-test) (run-tests run-sxml-tests))
        (rename (chibi syntax-case-test) (run-tests run-syntax-case-tests))
        (rename (chibi uri-test) (run-tests run-uri-tests))
        )

(test-begin "libraries")

(run-srfi-1-tests)
(run-srfi-2-tests)
(run-srfi-16-tests)
(run-srfi-26-tests)
(run-srfi-38-tests)
(run-srfi-41-tests)
(run-srfi-69-tests)
(run-srfi-99-tests)
(run-srfi-117-tests)
(run-srfi-121-tests)
(run-srfi-127-tests)
(run-srfi-129-tests)
(run-srfi-130-tests)
(run-srfi-133-tests)
(run-srfi-134-tests)
(run-srfi-139-tests)
(run-srfi-151-tests)
(run-srfi-158-tests)
(run-srfi-211-tests)
(run-srfi-219-tests)
(run-srfi-229-tests)
(run-srfi-253-tests)
(run-srfi-273-tests)
(run-scheme-bytevector-tests)
(run-assert-tests)
(run-base64-tests)
(run-bytevector-tests)
(run-md5-tests)
(run-generic-tests)
(run-iset-tests)
(run-loop-tests)
(run-match-tests)
(run-mime-tests)
(run-numeric-tests)
(run-parse-tests)
(run-pathname-tests)
(run-regexp-tests)
(run-scribble-tests)
(run-string-tests)
(run-syntax-case-tests)
(run-sxml-tests)
(run-uri-tests)

(test-end)
