#!/usr/bin/env python3
"""Build puchi/puchi.h from the upstream Chibi sources in this repository.

Steps (each one is a function below, called in order by main()):
  1. copy_upstream     copy the upstream tree into puchi/build/src
  2. apply_patches     git apply puchi/patches/*.patch to that copy
  3. write_install_h   generate include/chibi/install.h (Chibi's Makefile does this)
  4. build_host_chibi  build a stock chibi-scheme in puchi/build/host (or use --chibi)
  5. run_chibi_ffi     generate C from the .stub files of bundled C libraries
  6. write_clibs_c     generate the static library table eval.c includes
  7. write_files_c     embed init-7.scm, meta-7.scm and every bundled library file
  8. inline            expand puchi/src/puchi.h.in into puchi/puchi.h

Nothing outside puchi/ is modified.  The output is deterministic.
"""
import argparse
import os
import re
import shutil
import subprocess
import sys

PUCHI = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.dirname(PUCHI)
BUILD = os.path.join(PUCHI, "build")
SRC = os.path.join(BUILD, "src")      # patched copy of upstream
GEN = os.path.join(BUILD, "gen")      # generated files
HOST = os.path.join(BUILD, "host")    # stock chibi used to run chibi-ffi

# ---------------------------------------------------------------------------
# Configuration: what goes into the amalgamation.

# Module directory name.  install.h sets sexp_default_module_path to this, the
# embedded files live under it, and static library names start with it.
MODULE_DIR = "lib"

# Libraries the embedded file set is computed from (transitively, following
# import, include and include-shared).  R7RS-small, plus (puchi host).
ROOT_LIBRARIES = [
    "scheme base", "scheme case-lambda", "scheme char", "scheme complex",
    "scheme cxr", "scheme eval", "scheme file", "scheme inexact",
    "scheme lazy", "scheme load", "scheme process-context", "scheme read",
    "scheme repl", "scheme time", "scheme write", "scheme r5rs",
    "scheme small",  # the interaction environment made by puchi_open
    "puchi host",
]

# Features assumed when following cond-expand in .sld files.  Over-including
# is harmless (a few extra embedded files); under-including makes an import
# fail at run time, which the test suite catches.
SLD_FEATURES = {"chibi", "puchi", "r7rs", "full-unicode", "ratios",
                "exact-closed", "exact-complex", "ieee-float", "modules",
                "uvector", "little-endian", "big-endian", "else"}

# C libraries compiled in: include-shared name -> C source and .stub (if the
# C source is generated by chibi-ffi).  Every include-shared reached from
# ROOT_LIBRARIES must be listed here or in PUCHI_C_LIBRARIES.
C_LIBRARIES = {
    "srfi/69/hash": {"c": "lib/srfi/69/hash.c"},
    "chibi/ast": {"c": "lib/chibi/ast.c"},
    "srfi/151/bit": {"c": "lib/srfi/151/bit.c"},
    "chibi/io/io": {"c": "lib/chibi/io/io.c", "stub": "lib/chibi/io/io.stub"},
    "srfi/39/param": {"c": "lib/srfi/39/param.c"},
}
# C libraries implemented by puchi itself (init function in src/puchi_glue.c).
PUCHI_C_LIBRARIES = {"puchi/host": "puchi_init_host_library"}

# Upstream files that are never compiled in this configuration.  An #include
# of one of them is replaced by an #error, so if a configuration change ever
# makes such an include live, compilation fails loudly.
NOT_INLINED = {"opt/x86.c", "opt/plan9-opcodes.c", "chibi/sexp-hufftabs.h",
               "chibi/sexp-huff.h", "chibi/sexp-unhuff.h",
               "gc/gc.h"}  # Boehm GC (SEXP_USE_BOEHM)

# ---------------------------------------------------------------------------

def die(msg):
    sys.exit("amalgamate: " + msg)


def run(cmd, cwd=None, env=None):
    print("+", " ".join(cmd))
    subprocess.run(cmd, cwd=cwd, env=env, check=True)


def read(path):
    with open(path, "r", encoding="utf-8", newline="") as f:
        return f.read().replace("\r\n", "\n")


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def copy_upstream():
    """Fresh copy of the files git tracks, outside puchi/.

    Only tracked files: stale build products in the work tree (clibs.c,
    generated lib/**/*.c, install.h) must never leak into the amalgamation.
    """
    if os.path.isdir(SRC):
        shutil.rmtree(SRC)
    names = subprocess.run(["git", "ls-files", "-z"], cwd=ROOT, check=True,
                           stdout=subprocess.PIPE).stdout.decode("utf-8").split("\0")
    for name in names:
        if not name or name.startswith("puchi/"):
            continue
        dst = os.path.join(SRC, name)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(os.path.join(ROOT, name), dst)


def apply_patches():
    patches = sorted(f for f in os.listdir(os.path.join(PUCHI, "patches"))
                     if f.endswith(".patch"))
    for p in patches:
        # --directory makes git apply work on the copy, not the work tree.
        run(["git", "apply", "-p1", "--whitespace=nowarn",
             "--directory=" + os.path.relpath(SRC, ROOT).replace(os.sep, "/"),
             os.path.join("puchi", "patches", p)], cwd=ROOT)


def write_install_h():
    version = read(os.path.join(ROOT, "VERSION")).strip()
    release = read(os.path.join(ROOT, "RELEASE")).strip()
    text = read(os.path.join(PUCHI, "src", "install.h.in"))
    text = text.replace("@VERSION@", version).replace("@RELEASE@", release)
    text = text.replace("@MODULE_DIR@", MODULE_DIR)
    write(os.path.join(SRC, "include", "chibi", "install.h"), text)
    return version


def build_host_chibi(chibi):
    """Return a command prefix that runs chibi-scheme with its own libraries."""
    env = dict(os.environ)
    if chibi:
        return [chibi], env
    exe = os.path.join(HOST, "chibi-scheme")
    if not os.path.exists(exe):
        if os.path.isdir(HOST):
            shutil.rmtree(HOST)
        # stock (unpatched) sources: chibi-ffi only needs a working chibi
        names = subprocess.run(["git", "ls-files", "-z"], cwd=ROOT, check=True,
                               stdout=subprocess.PIPE).stdout.decode("utf-8").split("\0")
        for name in names:
            if name and not name.startswith("puchi/"):
                dst = os.path.join(HOST, name)
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                shutil.copy2(os.path.join(ROOT, name), dst)
        run(["make", "-j4", "chibi-scheme"], cwd=HOST)
    env["LD_LIBRARY_PATH"] = HOST + os.pathsep + env.get("LD_LIBRARY_PATH", "")
    env["DYLD_LIBRARY_PATH"] = HOST + os.pathsep + env.get("DYLD_LIBRARY_PATH", "")
    env["CHIBI_MODULE_PATH"] = os.path.join(HOST, "lib")
    return [exe, "-q"], env


def run_chibi_ffi(chibi_cmd, env):
    for lib in C_LIBRARIES.values():
        if "stub" in lib:
            run(chibi_cmd + [os.path.join(HOST if os.path.isdir(HOST) else ROOT,
                                          "tools", "chibi-ffi"), lib["stub"]],
                cwd=SRC, env=env)
            if not os.path.exists(os.path.join(SRC, lib["c"])):
                die("chibi-ffi did not produce " + lib["c"])


# --- .sld dependency walker ------------------------------------------------

def sexp_tokens(text):
    text = re.sub(r"#\|.*?\|#", " ", text, flags=re.S)
    return re.findall(r'"(?:\\.|[^"\\])*"|;[^\n]*|[()]|[^\s()]+', text)


def sexp_parse(text):
    out, stack = [], []
    cur = out
    for t in sexp_tokens(text):
        if t.startswith(";"):
            continue
        if t == "(":
            stack.append(cur)
            cur.append([])
            cur = cur[-1]
        elif t == ")":
            cur = stack.pop()
        else:
            cur.append(t)
    return out


def feature_ok(req):
    if isinstance(req, str):
        return req in SLD_FEATURES
    if req and req[0] == "and":
        return all(feature_ok(x) for x in req[1:])
    if req and req[0] == "or":
        return any(feature_ok(x) for x in req[1:])
    if req and req[0] == "not":
        return not feature_ok(req[1])
    if req and req[0] == "library":
        return find_library_file(library_name(req[1]))[0] is not None
    return False


def library_name(spec):
    while isinstance(spec, list) and spec and spec[0] in (
            "only", "except", "prefix", "rename"):
        spec = spec[1]
    return " ".join(spec)


def find_library_file(name):
    rel = name.replace(" ", "/") + ".sld"
    for base in (os.path.join(PUCHI, "lib"), os.path.join(SRC, "lib")):
        if os.path.exists(os.path.join(base, rel)):
            return base, rel
    return None, rel


def collect_files():
    """Return ({relative path: absolute path}, [include-shared names])."""
    files, shared, seen = {}, [], set()
    todo = list(ROOT_LIBRARIES)

    def add(base, rel):
        files.setdefault(rel, os.path.join(base, rel))

    def walk(base, rel, decls):
        here = os.path.dirname(rel)
        for d in decls:
            if not isinstance(d, list) or not d:
                continue
            if d[0] == "import":
                todo.extend(library_name(s) for s in d[1:])
            elif d[0] in ("include", "include-ci", "include-library-declarations"):
                for f in d[1:]:
                    inc = os.path.normpath(os.path.join(here, f.strip('"'))).replace(os.sep, "/")
                    b = base if os.path.exists(os.path.join(base, inc)) else os.path.join(SRC, "lib")
                    add(b, inc)
            elif d[0] in ("include-shared", "include-shared-optionally"):
                shared.append(os.path.join(here, d[1].strip('"')).replace(os.sep, "/"))
            elif d[0] == "cond-expand":
                for clause in d[1:]:
                    if feature_ok(clause[0]):
                        walk(base, rel, clause[1:])
                        break

    while todo:
        name = todo.pop()
        if name in seen or name in ("chibi", "meta"):
            continue  # (chibi) and (meta) are built into meta-7.scm
        seen.add(name)
        base, rel = find_library_file(name)
        if base is None:
            die("library not found: (%s)" % name)
        add(base, rel)
        for form in sexp_parse(read(os.path.join(base, rel))):
            if isinstance(form, list) and form and form[0] == "define-library":
                walk(base, rel, form[2:])
    for f in ("init-7.scm", "meta-7.scm"):
        add(os.path.join(SRC, "lib"), f)
    return files, sorted(set(shared))


def c_chunks(data):
    """C string literals of at most ~4000 bytes each, split at line ends.

    MSVC rejects a single literal longer than 16380 bytes (C2026) and a
    concatenation longer than 65535 bytes, so files are stored as arrays of
    separate literals instead of one big literal.
    """
    chunks, cur, size = [], [], 0
    for line in data.decode("utf-8").splitlines(keepends=True):
        b = line.encode("utf-8")
        if cur and size + len(b) > 4000:
            chunks.append(cur)
            cur, size = [], 0
        cur.append(b)
        size += len(b)
    if cur:
        chunks.append(cur)
    out = []
    for chunk in chunks:
        lits = []
        for b in chunk:
            s = []
            for byte in b:
                c = chr(byte)
                if c == "\\":
                    s.append("\\\\")
                elif c == '"':
                    s.append('\\"')
                elif c == "\n":
                    s.append("\\n")
                elif c == "\t":
                    s.append("\\t")
                elif 32 <= byte < 127 and c != "?":   # '?' avoids trigraphs
                    s.append(c)
                else:
                    s.append("\\%03o" % byte)
            lits.append('    "%s"' % "".join(s))
        out.append("\n".join(lits))
    return out


def write_files_c(files):
    """Embedded files, sorted by path (binary search at run time)."""
    parts = ["/* generated by puchi/tools/amalgamate.py: embedded library files */\n"]
    names = sorted(files)
    for i, rel in enumerate(names):
        with open(files[rel], "rb") as f:
            data = f.read().replace(b"\r\n", b"\n")
        chunks = c_chunks(data) or ['    ""']
        parts.append("static const char *const puchi_file_%d[] = {\n%s,\n  NULL};\n"
                     % (i, ",\n".join(chunks)))
    parts.append("static const struct puchi_embedded_file puchi_embedded_files[] = {\n")
    for i, rel in enumerate(names):
        parts.append('  {"%s/%s", puchi_file_%d},\n' % (MODULE_DIR, rel, i))
    parts.append("};\n")
    write(os.path.join(GEN, "puchi_files.c"), "".join(parts))


def write_clibs_c(shared):
    for name in shared:
        if name not in C_LIBRARIES and name not in PUCHI_C_LIBRARIES:
            die("include-shared \"%s\" is not in C_LIBRARIES" % name)
    lines = ["/* generated by puchi/tools/amalgamate.py: bundled C libraries */\n"]
    entries = []
    proto = ("static sexp %s(sexp ctx, sexp self, sexp_sint_t n, sexp env, "
             "const char* version, const sexp_abi_identifier_t abi);\n")
    for name in sorted(C_LIBRARIES):
        init = "sexp_init_lib_" + re.sub(r"[^A-Za-z0-9]", "_", name)
        # the static declaration gives each library's init function (all
        # named sexp_init_library upstream) its own name and internal linkage
        lines.append(proto % init)
        lines.append("#define sexp_init_library %s\n#include \"%s\"\n#undef sexp_init_library\n"
                     % (init, C_LIBRARIES[name]["c"]))
        entries.append((name, init))
    for name, init in sorted(PUCHI_C_LIBRARIES.items()):
        lines.append(proto % init)
        entries.append((name, init))
    lines.append("static struct sexp_library_entry_t sexp_static_libraries_array[] = {\n")
    for name, init in entries:
        lines.append('  {"%s/%s", %s},\n' % (MODULE_DIR, name, init))
    lines.append("  {NULL, NULL}\n};\n")
    lines.append("static struct sexp_library_entry_t* sexp_static_libraries = "
                 "sexp_static_libraries_array;\n")
    write(os.path.join(GEN, "clibs.c"), "".join(lines))


# --- include inliner ---------------------------------------------------------

INCLUDE_RE = re.compile(r'^\s*#\s*include\s*([<"])([^>"]+)[>"]')


def has_include_guard(text):
    """True if the file starts (after comments) with #ifndef X / #define X."""
    body = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    lines = [l.strip() for l in body.splitlines() if l.strip() and not l.strip().startswith("//")]
    if len(lines) < 2:
        return False
    m = re.match(r"#\s*ifndef\s+(\w+)$", lines[0])
    return bool(m) and re.match(r"#\s*define\s+%s\b" % m.group(1), lines[1]) is not None


def inline(path, search, seen, out):
    """Append path to out, recursively replacing #include of local files.

    A file with an include guard is inlined only the first time it is met;
    later includes of it would expand to nothing anyway.  System headers
    (<stdio.h> ...) are left as #include lines.
    """
    text = read(path)
    if has_include_guard(text):
        if path in seen:
            out.append("/* puchi: already included: %s */\n" % os.path.relpath(path, BUILD).replace(os.sep, "/"))
            return
        seen.add(path)
    for line in text.splitlines(keepends=True):
        m = INCLUDE_RE.match(line)
        if not m:
            out.append(line)
            continue
        kind, name = m.groups()
        if name in NOT_INLINED:
            out.append('#error "puchi: %s is not part of the amalgamation"\n' % name)
            continue
        dirs = ([os.path.dirname(path)] if kind == '"' else []) + search
        target = None
        if kind == '"' or name.startswith("chibi/"):
            for d in dirs:
                cand = os.path.normpath(os.path.join(d, name))
                if os.path.isfile(cand):
                    target = cand
                    break
            if target is None and kind == '"':
                die("cannot resolve #include \"%s\" in %s" % (name, path))
        if target is None:
            out.append(line)  # a system header, kept as is
        else:
            out.append("/* puchi: begin %s */\n" % os.path.relpath(target, BUILD).replace(os.sep, "/"))
            inline(target, search, seen, out)
            out.append("/* puchi: end %s */\n" % os.path.relpath(target, BUILD).replace(os.sep, "/"))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--chibi", help="existing chibi-scheme to run chibi-ffi with")
    args = ap.parse_args()

    copy_upstream()
    apply_patches()
    version = write_install_h()
    chibi_cmd, env = build_host_chibi(args.chibi)
    run_chibi_ffi(chibi_cmd, env)
    files, shared = collect_files()
    write_clibs_c(shared)
    write_files_c(files)

    search = [os.path.join(SRC, "include"), SRC, os.path.join(PUCHI, "src"), GEN]
    out = []
    inline(os.path.join(PUCHI, "src", "puchi.h.in"), search, set(), out)
    text = "".join(out).replace("@VERSION@", version)
    write(os.path.join(PUCHI, "puchi.h"), text)
    print("amalgamate: wrote puchi/puchi.h (%d bytes, %d embedded files)"
          % (len(text.encode("utf-8")), len(files)))


if __name__ == "__main__":
    main()
